// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.0
// source: ioctrl.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_RED   Color = 0
	Color_GREEN Color = 1
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "RED",
		1: "GREEN",
	}
	Color_value = map[string]int32{
		"RED":   0,
		"GREEN": 1,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_ioctrl_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_ioctrl_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{0}
}

type SetLEDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusLedColor Color `protobuf:"varint,1,opt,name=statusLedColor,proto3,enum=canf22g2.grpc.Color" json:"statusLedColor,omitempty"` // set status LED color
	RecLedOn       bool  `protobuf:"varint,2,opt,name=recLedOn,proto3" json:"recLedOn,omitempty"`                                      // on/off recording led (true/false)
	Channel        int32 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`                                        // channel 0 or 1
}

func (x *SetLEDsRequest) Reset() {
	*x = SetLEDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ioctrl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLEDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLEDsRequest) ProtoMessage() {}

func (x *SetLEDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioctrl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLEDsRequest.ProtoReflect.Descriptor instead.
func (*SetLEDsRequest) Descriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{0}
}

func (x *SetLEDsRequest) GetStatusLedColor() Color {
	if x != nil {
		return x.StatusLedColor
	}
	return Color_RED
}

func (x *SetLEDsRequest) GetRecLedOn() bool {
	if x != nil {
		return x.RecLedOn
	}
	return false
}

func (x *SetLEDsRequest) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type SetLEDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetLEDsResponse) Reset() {
	*x = SetLEDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ioctrl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLEDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLEDsResponse) ProtoMessage() {}

func (x *SetLEDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioctrl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLEDsResponse.ProtoReflect.Descriptor instead.
func (*SetLEDsResponse) Descriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{1}
}

func (x *SetLEDsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLEDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel int32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"` // specify which channel to query
}

func (x *GetLEDsRequest) Reset() {
	*x = GetLEDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ioctrl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLEDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLEDsRequest) ProtoMessage() {}

func (x *GetLEDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioctrl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLEDsRequest.ProtoReflect.Descriptor instead.
func (*GetLEDsRequest) Descriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{2}
}

func (x *GetLEDsRequest) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type GetLEDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusLedColor Color `protobuf:"varint,1,opt,name=statusLedColor,proto3,enum=canf22g2.grpc.Color" json:"statusLedColor,omitempty"`
	RecLedOn       bool  `protobuf:"varint,2,opt,name=recLedOn,proto3" json:"recLedOn,omitempty"`
	Channel        int32 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *GetLEDsResponse) Reset() {
	*x = GetLEDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ioctrl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLEDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLEDsResponse) ProtoMessage() {}

func (x *GetLEDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioctrl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLEDsResponse.ProtoReflect.Descriptor instead.
func (*GetLEDsResponse) Descriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{3}
}

func (x *GetLEDsResponse) GetStatusLedColor() Color {
	if x != nil {
		return x.StatusLedColor
	}
	return Color_RED
}

func (x *GetLEDsResponse) GetRecLedOn() bool {
	if x != nil {
		return x.RecLedOn
	}
	return false
}

func (x *GetLEDsResponse) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

var File_ioctrl_proto protoreflect.FileDescriptor

var file_ioctrl_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6f, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x63, 0x61, 0x6e, 0x66, 0x32, 0x32, 0x67, 0x32, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x22, 0x84, 0x01,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3c, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x64, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x61, 0x6e, 0x66, 0x32,
	0x32, 0x67, 0x32, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x0e,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x63, 0x4c, 0x65, 0x64, 0x4f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x72, 0x65, 0x63, 0x4c, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x85, 0x01,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x64, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x61, 0x6e, 0x66,
	0x32, 0x32, 0x67, 0x32, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52,
	0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x65, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x4c, 0x65, 0x64, 0x4f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x63, 0x4c, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2a, 0x1b, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x07,
	0x0a, 0x03, 0x52, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x45, 0x45, 0x4e,
	0x10, 0x01, 0x32, 0xa4, 0x01, 0x0a, 0x0a, 0x4c, 0x45, 0x44, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4a, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73, 0x12, 0x1d, 0x2e, 0x63,
	0x61, 0x6e, 0x66, 0x32, 0x32, 0x67, 0x32, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74,
	0x4c, 0x45, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x61,
	0x6e, 0x66, 0x32, 0x32, 0x67, 0x32, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x4c,
	0x45, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73, 0x12, 0x1d, 0x2e, 0x63, 0x61, 0x6e, 0x66, 0x32,
	0x32, 0x67, 0x32, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x61, 0x6e, 0x66, 0x32, 0x32,
	0x67, 0x32, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x45, 0x44, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x61, 0x6e,
	0x66, 0x32, 0x32, 0x67, 0x32, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ioctrl_proto_rawDescOnce sync.Once
	file_ioctrl_proto_rawDescData = file_ioctrl_proto_rawDesc
)

func file_ioctrl_proto_rawDescGZIP() []byte {
	file_ioctrl_proto_rawDescOnce.Do(func() {
		file_ioctrl_proto_rawDescData = protoimpl.X.CompressGZIP(file_ioctrl_proto_rawDescData)
	})
	return file_ioctrl_proto_rawDescData
}

var file_ioctrl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ioctrl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ioctrl_proto_goTypes = []any{
	(Color)(0),              // 0: canf22g2.grpc.Color
	(*SetLEDsRequest)(nil),  // 1: canf22g2.grpc.SetLEDsRequest
	(*SetLEDsResponse)(nil), // 2: canf22g2.grpc.SetLEDsResponse
	(*GetLEDsRequest)(nil),  // 3: canf22g2.grpc.GetLEDsRequest
	(*GetLEDsResponse)(nil), // 4: canf22g2.grpc.GetLEDsResponse
}
var file_ioctrl_proto_depIdxs = []int32{
	0, // 0: canf22g2.grpc.SetLEDsRequest.statusLedColor:type_name -> canf22g2.grpc.Color
	0, // 1: canf22g2.grpc.GetLEDsResponse.statusLedColor:type_name -> canf22g2.grpc.Color
	1, // 2: canf22g2.grpc.LEDService.SetLEDs:input_type -> canf22g2.grpc.SetLEDsRequest
	3, // 3: canf22g2.grpc.LEDService.GetLEDs:input_type -> canf22g2.grpc.GetLEDsRequest
	2, // 4: canf22g2.grpc.LEDService.SetLEDs:output_type -> canf22g2.grpc.SetLEDsResponse
	4, // 5: canf22g2.grpc.LEDService.GetLEDs:output_type -> canf22g2.grpc.GetLEDsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ioctrl_proto_init() }
func file_ioctrl_proto_init() {
	if File_ioctrl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ioctrl_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SetLEDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ioctrl_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetLEDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ioctrl_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetLEDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ioctrl_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetLEDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ioctrl_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ioctrl_proto_goTypes,
		DependencyIndexes: file_ioctrl_proto_depIdxs,
		EnumInfos:         file_ioctrl_proto_enumTypes,
		MessageInfos:      file_ioctrl_proto_msgTypes,
	}.Build()
	File_ioctrl_proto = out.File
	file_ioctrl_proto_rawDesc = nil
	file_ioctrl_proto_goTypes = nil
	file_ioctrl_proto_depIdxs = nil
}
